### ISSUE TITLE
trainval.txt not found

### ISSUE THREAD

**Issue by Shpionus** [priya-dwivedi/Deep-Learning#3]
Hi, I not found trainval.txt file in tensorflow_toy_detector, but it required for create_pet_tf_record.py

```$ python create_pet_tf_record.py --label_map_path=toy_label_map.pbtxt --data_dir=`pwd` --output_dir=`pwd` ```
```
Traceback (most recent call last):
  File "create_pet_tf_record.py", line 213, in <module>
    tf.app.run()
  File "project/.tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "create_pet_tf_record.py", line 192, in main
    examples_list = dataset_util.read_examples_list(examples_path)
  File "project/models/research/object_detection/utils/dataset_util.py", line 59, in read_examples_list
    lines = fid.readlines()
  File "project/.tensorflow/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 181, in readlines
    self._preread_check()
  File "project/.tensorflow/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "project/.tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: project/Deep-Learning/tensorflow_toy_detector/annotations/trainval.txt
```

**Comment by priya-dwivedi** [comment]
You can write a code to create it. Please checkout the link below:

https://stackoverflow.com/questions/44973184/train-tensorflow-object-detection-on-own-dataset
