### ISSUE TITLE
No module named 'object_detection'

### ISSUE THREAD

**Issue by NguyenTam1997** [priya-dwivedi/Deep-Learning#5]
When I Creating the TFR datasets
Error:
Traceback (most recent call last):
  File "C:\Users\NguyenThiTam\Desktop\DEMO\create_pet_tf_records.py", line 189, in <module>
    tf.app.run()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Users\NguyenThiTam\Desktop\DEMO\create_pet_tf_records.py", line 162, in main
    label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  File "C:\Users\NguyenThiTam\Desktop\KLTN\models\research\object_detection\utils\label_map_util.py", line 137, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "C:\Users\NguyenThiTam\Desktop\KLTN\models\research\object_detection\utils\label_map_util.py", line 117, in load_labelmap
    label_map_string = fid.read()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 119, in read
    self._preread_check()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: data/pet_label_map.pbtxt : The system cannot find the file specified.

; No such file or directory

Sorry. my English is not good. Thank you!

**Comment by karkinissan** [comment]
Open CMD in the \research directory and run 

> SET PYTHONPATH=%cd%:%cd%\slim
