### ISSUE TITLE
create_pet_tf_record.py error in toy example (Mask R-CNNN)

### ISSUE THREAD

**Issue by gireeshkbogu** [priya-dwivedi/Deep-Learning#69]
I am trying to replicate the result of toy example but getting the following error when I try to run this script.

`$ python create_pet_tf_record.py --data_dir=toy_example_mask_rcnn/images --output_dir=toy_example_mask_rcnn/output`

`
WARNING: Logging before flag parsing goes to stderr.
W0730 16:42:20.032857 47825674530496 deprecation_wrapper.py:119] From create_pet_tf_record.py:307: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0730 16:42:20.033967 47825674530496 deprecation_wrapper.py:119] From /srv/gsfs0/projects/snyder/gbogu17/packages_local/TensorFlow/models/research/object_detection/utils/label_map_util.py:137: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "/srv/gsfs0/projects/snyder/gbogu17/packages_local/TensorFlow/models/research/object_detection/utils/label_map_util.py", line 141, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 685, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 752, in MergeLines
    return parser.MergeLines(lines, message)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 777, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 799, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 924, in _MergeField
    merger(tokenizer, message, field)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 998, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 924, in _MergeField
    merger(tokenizer, message, field)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1049, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1420, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1435, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1454, in _ConsumeSingleByteString
    raise self.ParseError('Expected string but found: %r' % (text,))
google.protobuf.text_format.ParseError: 3:8 : ' name: ‘toy’': Expected string but found: '‘'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_pet_tf_record.py", line 307, in <module>
    tf.app.run()
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/scg/apps/software/tensorflow-gpu/1.14.0/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "create_pet_tf_record.py", line 262, in main
    label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  File "/srv/gsfs0/projects/snyder/gbogu17/packages_local/TensorFlow/models/research/object_detection/utils/label_map_util.py", line 169, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/srv/gsfs0/projects/snyder/gbogu17/packages_local/TensorFlow/models/research/object_detection/utils/label_map_util.py", line 143, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'`

**Comment by naserpiltan** [comment]
@gireeshkbogu did you solve the problem ?
